### ISSUE TITLE
Criar funcionalidade para Quiz

### ISSUE THREAD

**Issue by Sergio-Daniel-Pires** [Sergio-Daniel-Pires/BlueSaver#3]
Criar as seguintes rotas:
/gerar
Rota recebe um parâmetro "Dificuldade" e devolve um questionário de N perguntas da seguinte forma:
```
Quiz {Dificuldade escolhida}
Pergunta 1: xxxxx
a) x1
b) x2
c) x3
Pergunta 2: yyyyy
a) y1
b) y2
c) y3
Pergunta 3: zzzzz
a) z1
b) z2
c) z3
```

/responder
Rota recebe um parâmetro "Dificuldade" e "Resposta 1/2/3" e devolve a quantidade de acertos naquele questionário, exemplo:
```
Sua Pontuação no quiz {Dificuldade} foi acertos/total!
```
No caso, começaremos com 3 perguntas, podendo aumentar depois.

**Comment by Sergio-Daniel-Pires** [comment]
Exemplo de formato que pode ser utilizado para salvar as perguntas:
```json
{
    "Médio": {
        "1": {
            "Pergunta": "Qual a formula da agua?",
            "Opcoes": {
                "a": "H2O",
                "b": "NaCl",
                "c": "CaO"
            },
            "Correta": "a"
        }
    }
}
```

**Comment by TorMenezes** [comment]
Essa Issure será dividida em 3 partes: 
I- Criar os arquivos Json das perguntas
II- Criar a funcionalidade de mostrar as perguntas dependendo da dificuldade
III- Criar a funcionalidade de coletar as respostas e devolver os acertos dependendo da dificuldade
