### ISSUE TITLE
Adicionar versão das depêndencias

### ISSUE THREAD

**Issue by Ygor-J** [Sergio-Daniel-Pires/BlueSaver#5]
Adicionar no requirements.txt as versões das depêndencias

**Comment by Sergio-Daniel-Pires** [comment]
Ygor, segue as versões que eu utilizei:
Python          3.10.6
pytest           7.3.1
Flask             2.3.0
flask-restx    1.1.0

Poderia atualizar junto da Issue https://github.com/Sergio-Daniel-Pires/BlueSaver/issues/2?

**Comment by Ygor-J** [comment]
Adicionado.

**Comment by Sergio-Daniel-Pires** [comment]
@Ygor-J Poderia adicionar no README.MD como instalar os requirements antes da parte de rodar o servidor?

**Comment by Ygor-J** [comment]
Instruções adicionadas
